new options -z and --zmax & windows ugrep-indexer.exe
- new option -z to index archives and compressed files
- new option --zmax=NUM to specify nesting depth of archives to index
- new ugrep-indexer.exe Windows version

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -768,6 +768,8 @@ with_bzlib
 with_lzma
 with_lz4
 with_zstd
+with_brotli
+with_bzip3
 '
       ac_precious_vars='build_alias
 host_alias
@@ -1432,6 +1434,15 @@ Optional Packages:
   --with-zstd=DIR         root directory path of zstd installation [defaults to
                           /usr/local or /usr if not found in /usr/local]
   --without-zstd          to disable zstd usage completely
+  --with-brotli=DIR       root directory path of brotli library installation
+                          [defaults to /usr/local or /usr if not found in
+                          /usr/local]
+  --without-brotli        to disable brotli library usage completely
+  --with-bzip3            to enable bzip3 library to decompress .bz3 files
+  --with-bzip3=DIR        root directory path of bzip3 library installation
+                          [defaults to /usr/local or /usr if not found in
+                          /usr/local]
+  --without-bzip3         to disable bzip3 library usage completely
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -6952,7 +6963,7 @@ printf "%s\n" "#define HAVE_LIBZ 1" >>confdefs.h
     #
     # If either header or library was not found, action-if-not-found
     #
-    echo "zlib not found: ugrep-indexer option -z is not available"
+    echo "recommended zlib not found: ugrep-indexer option -z is disabled"
   fi
 fi
 
@@ -6995,16 +7006,16 @@ then
   # check the user supplied or any other more or less 'standard' place:
   #   Most UNIX systems      : /usr/local and /usr
   #   MacPorts / Fink on OSX : /opt/local respectively /sw
-  for BZLIB_HOME in ${bzlib_places} ; do
-    if test -f "${BZLIB_HOME}/include/bzlib.h"; then break; fi
-    BZLIB_HOME=""
+  for BZ2LIB_HOME in ${bzlib_places} ; do
+    if test -f "${BZ2LIB_HOME}/include/bzlib.h"; then break; fi
+    BZ2LIB_HOME=""
   done
 
-  BZLIB_OLD_LDFLAGS=$LDFLAGS
-  BZLIB_OLD_CPPFLAGS=$CPPFLAGS
-  if test -n "${BZLIB_HOME}"; then
-    LDFLAGS="$LDFLAGS -L${BZLIB_HOME}/lib"
-    CPPFLAGS="$CPPFLAGS -I${BZLIB_HOME}/include"
+  BZ2LIB_OLD_LDFLAGS=$LDFLAGS
+  BZ2LIB_OLD_CPPFLAGS=$CPPFLAGS
+  if test -n "${BZ2LIB_HOME}"; then
+    LDFLAGS="$LDFLAGS -L${BZ2LIB_HOME}/lib"
+    CPPFLAGS="$CPPFLAGS -I${BZ2LIB_HOME}/include"
   fi
   ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -7074,8 +7085,8 @@ ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
     # If both library and header were found, action-if-found
     #
 
-                CPPFLAGS="$CPPFLAGS -I${BZLIB_HOME}/include"
-                LDFLAGS="$LDFLAGS -L${BZLIB_HOME}/lib"
+                CPPFLAGS="$CPPFLAGS -I${BZ2LIB_HOME}/include"
+                LDFLAGS="$LDFLAGS -L${BZ2LIB_HOME}/lib"
                 LIBS="-lbz2 $LIBS"
 
 printf "%s\n" "#define HAVE_LIBBZ2 1" >>confdefs.h
@@ -7085,7 +7096,7 @@ printf "%s\n" "#define HAVE_LIBBZ2 1" >>confdefs.h
     #
     # If either header or library was not found, action-if-not-found
     #
-    echo "libbz2 not found: ugrep-indexer option -z won't index .bz and .bz2 files"
+    echo "recommended libbz2 not found: ugrep-indexer option -z cannot index .bz and .bz2 files"
   fi
 fi
 
@@ -7218,7 +7229,7 @@ printf "%s\n" "#define HAVE_LIBLZMA 1" >>confdefs.h
     #
     # If either header or library was not found, action-if-not-found
     #
-    echo "liblzma not found: ugrep-indexer option -z won't index .lzma and .xz files"
+    echo "recommended liblzma not found: ugrep-indexer option -z cannot index .lzma and .xz files"
   fi
 fi
 
@@ -7351,7 +7362,7 @@ printf "%s\n" "#define HAVE_LIBLZ4 1" >>confdefs.h
     #
     # If either header or library was not found, action-if-not-found
     #
-    echo "liblz4 not found: ugrep-indexer option -z won't index .lz4 files"
+    echo "optional liblz4 not found: install if you want ugrep-indexer option -z to index .lz4 files"
   fi
 fi
 
@@ -7484,10 +7495,290 @@ printf "%s\n" "#define HAVE_LIBZSTD 1" >>confdefs.h
     #
     # If either header or library was not found, action-if-not-found
     #
-    echo "libzstd not found: ugrep-indexer option -z won't index .zst files"
+    echo "optional libzstd not found: install if you want ugrep-indexer option -z to index .zst files"
   fi
 fi
 
+
+#
+# Handle user hints
+#
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking if brotli is wanted" >&5
+printf %s "checking if brotli is wanted... " >&6; }
+brotli_places="/usr/local /usr /opt/homebrew /opt/local /sw"
+
+# Check whether --with-brotli was given.
+if test ${with_brotli+y}
+then :
+  withval=$with_brotli; if test "$withval" != "no" ; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+  if test -d "$withval"
+  then
+    brotli_places="$withval $brotli_places"
+  else
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Sorry, $withval does not exist, checking usual places" >&5
+printf "%s\n" "$as_me: WARNING: Sorry, $withval does not exist, checking usual places" >&2;}
+  fi
+else
+  brotli_places=""
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+fi
+else $as_nop
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+fi
+
+#
+# Locate brotli, if wanted
+#
+if test -n "${brotli_places}"
+then
+  # check the user supplied or any other more or less 'standard' place:
+  #   Most UNIX systems      : /usr/local and /usr
+  #   MacPorts / Fink on OSX : /opt/local respectively /sw
+  for BROTLI_HOME in ${brotli_places} ; do
+    if test -f "${BROTLI_HOME}/include/brotli/decode.h"; then break; fi
+    BROTLI_HOME=""
+  done
+
+  BROTLI_OLD_LDFLAGS=$LDFLAGS
+  BROTLI_OLD_CPPFLAGS=$CPPFLAGS
+  if test -n "${BROTLI_HOME}"; then
+    LDFLAGS="$LDFLAGS -L${BROTLI_HOME}/lib"
+    CPPFLAGS="$CPPFLAGS -I${BROTLI_HOME}/include"
+  fi
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for BrotliDecoderCreateInstance in -lbrotlidec" >&5
+printf %s "checking for BrotliDecoderCreateInstance in -lbrotlidec... " >&6; }
+if test ${ac_cv_lib_brotlidec_BrotliDecoderCreateInstance+y}
+then :
+  printf %s "(cached) " >&6
+else $as_nop
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lbrotlidec  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+char BrotliDecoderCreateInstance ();
+int
+main (void)
+{
+return BrotliDecoderCreateInstance ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"
+then :
+  ac_cv_lib_brotlidec_BrotliDecoderCreateInstance=yes
+else $as_nop
+  ac_cv_lib_brotlidec_BrotliDecoderCreateInstance=no
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_brotlidec_BrotliDecoderCreateInstance" >&5
+printf "%s\n" "$ac_cv_lib_brotlidec_BrotliDecoderCreateInstance" >&6; }
+if test "x$ac_cv_lib_brotlidec_BrotliDecoderCreateInstance" = xyes
+then :
+  brotli_cv_libbrotli=yes
+else $as_nop
+  brotli_cv_libbrotli=no
+fi
+
+  ac_fn_c_check_header_compile "$LINENO" "brotli/decode.h" "ac_cv_header_brotli_decode_h" "$ac_includes_default"
+if test "x$ac_cv_header_brotli_decode_h" = xyes
+then :
+  brotli_cv_brotli_h=yes
+else $as_nop
+  brotli_cv_brotli_h=no
+fi
+
+  ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  if test "$brotli_cv_libbrotli" = "yes" && test "$brotli_cv_brotli_h" = "yes"
+  then
+    #
+    # If both library and header were found, action-if-found
+    #
+
+                CPPFLAGS="$CPPFLAGS -I${BROTLI_HOME}/include"
+                LDFLAGS="$LDFLAGS -L${BROTLI_HOME}/lib"
+                LIBS="-lbrotlidec -lbrotlienc $LIBS"
+
+printf "%s\n" "#define HAVE_LIBBROTLI 1" >>confdefs.h
+
+
+  else
+    #
+    # If either header or library was not found, action-if-not-found
+    #
+    echo "optional brotli library not found: install if you want ugrep-indexer option -z to index .br files"
+  fi
+fi
+
+
+
+# Check whether --with-bzip3 was given.
+if test ${with_bzip3+y}
+then :
+  withval=$with_bzip3; with_bzip3_library="$withval"
+else $as_nop
+  with_bzip3_library=""
+fi
+
+if test "x$with_bzip3_library" != "x"; then
+  if test "x$with_bzip3" = "xyes"; then
+    unset with_bzip3
+  fi
+  #
+# Handle user hints
+#
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking if bzip3 is wanted" >&5
+printf %s "checking if bzip3 is wanted... " >&6; }
+bzip3_places="/usr/local /usr /opt/homebrew /opt/local /sw"
+
+# Check whether --with-bzip3 was given.
+if test ${with_bzip3+y}
+then :
+  withval=$with_bzip3; if test "$withval" != "no" ; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+  if test -d "$withval"
+  then
+    bzip3_places="$withval $bzip3_places"
+  else
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: Sorry, $withval does not exist, checking usual places" >&5
+printf "%s\n" "$as_me: WARNING: Sorry, $withval does not exist, checking usual places" >&2;}
+  fi
+else
+  bzip3_places=""
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+fi
+else $as_nop
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+fi
+
+#
+# Locate bzip3 library, if wanted
+#
+if test -n "${bzip3_places}"
+then
+  # check the user supplied or any other more or less 'standard' place:
+  #   Most UNIX systems      : /usr/local and /usr
+  #   MacPorts / Fink on OSX : /opt/local respectively /sw
+  for BZIP3_HOME in ${bzip3_places} ; do
+    if test -f "${BZIP3_HOME}/include/libbz3.h"; then break; fi
+    BZIP3_HOME=""
+  done
+
+  BZIP3_OLD_LDFLAGS=$LDFLAGS
+  BZIP3_OLD_CPPFLAGS=$CPPFLAGS
+  if test -n "${BZIP3_HOME}"; then
+    LDFLAGS="$LDFLAGS -L${BZIP3_HOME}/lib"
+    CPPFLAGS="$CPPFLAGS -I${BZIP3_HOME}/include"
+  fi
+  ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for bz3_new in -lbzip3" >&5
+printf %s "checking for bz3_new in -lbzip3... " >&6; }
+if test ${ac_cv_lib_bzip3_bz3_new+y}
+then :
+  printf %s "(cached) " >&6
+else $as_nop
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lbzip3  $LIBS"
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+char bz3_new ();
+int
+main (void)
+{
+return bz3_new ();
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_link "$LINENO"
+then :
+  ac_cv_lib_bzip3_bz3_new=yes
+else $as_nop
+  ac_cv_lib_bzip3_bz3_new=no
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam \
+    conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_lib_bzip3_bz3_new" >&5
+printf "%s\n" "$ac_cv_lib_bzip3_bz3_new" >&6; }
+if test "x$ac_cv_lib_bzip3_bz3_new" = xyes
+then :
+  bzip3_cv_libbzip3=yes
+else $as_nop
+  bzip3_cv_libbzip3=no
+fi
+
+  ac_fn_c_check_header_compile "$LINENO" "libbz3.h" "ac_cv_header_libbz3_h" "$ac_includes_default"
+if test "x$ac_cv_header_libbz3_h" = xyes
+then :
+  bzip3_cv_libbz3_h=yes
+else $as_nop
+  bzip3_cv_libbz3_h=no
+fi
+
+  ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+  if test "$bzip3_cv_libbzip3" = "yes" && test "$bzip3_cv_libbz3_h" = "yes"
+  then
+    #
+    # If both library and header were found, action-if-found
+    #
+
+                CPPFLAGS="$CPPFLAGS -I${BZIP3_HOME}/include"
+                LDFLAGS="$LDFLAGS -L${BZIP3_HOME}/lib"
+                LIBS="-lbzip3 $LIBS"
+
+printf "%s\n" "#define HAVE_LIBBZIP3 1" >>confdefs.h
+
+
+  else
+    #
+    # If either header or library was not found, action-if-not-found
+    #
+    echo "optional libbzip3 not found: install if you want ugrep-indexer option -z to index .bz3 files"
+  fi
+fi
+
+fi
 
 PTHREAD_CFLAGS=""
 
